### PR TITLE
H1 -> H2

### PR DESCRIPTION
**Pull request by neuromusic**
changes suggested H1 headings to H2 headings (for a11y & napari hub compatibility) https://github.com/chanzuckerberg/napari-hub/issues/438#issuecomment-1063390925

### CODE REVIEW

**Comment by tlambert03** [comment]
so how does it work if the user provides a proper single h1 heading?  I see for pages rendered from the README, it looks like you strip the top level h1 and use the name of the package in an h1 at the top, right?  Is it safe to assume that the same applies here?  If so, I'd add to the top comment saying something like "don't add a top level (`#`) heading here ... "

**Comment by tlambert03** [comment]
@neuromusic, let me know if you think a comment would be appropriate here, and what happens if they do include a single h1.  I'll merge after hearing from you

**Comment by tlambert03** [comment]
@neuromusic, let me know if you think a comment would be appropriate here, and what happens if they do include a single h1.  I'll merge after hearing from you

**Comment by neuromusic** [comment]
I think a comment makes sense, but the behavior is going to change soon to be less confusing (see https://github.com/chanzuckerberg/napari-hub/issues/441 )

If you don't mind, I will add a comment in a follow-up PR once that lands

**Comment by tlambert03** [comment]
Thanks!

**Pull request merged**
