### PR TITLE
Add /.napari/DESCRIPTION.md to nudge developers on preferred format

### PR DESCRIPTION
**Pull request by DragaDoncila**
To keep the repository README and napari hub documentation separate, this PR adds a `.napari/DESCRIPTION.md` file ~(still need to add prompts for it) to show users the preferred format for documentation on the hub.~ with prompts for developers on information flow and the sections they could use. 

Also add message after generation to point users to this file.

### CODE REVIEW

**Comment by jni** [comment]
I think we should probably wait until the napari hub launches to merge this? I also think you want this to be fail-safe, meaning all the instructions should be in comments and the uncommented text should simply read something along the lines of "The developer has not yet provided a detailed description file". What do you think @DragaDoncila?

**Comment by DragaDoncila** [comment]
@jni I've updated that now. I'm curious why wait until launch to merge? Ideally we could have new plugins already making use of the napari hub specific description - plus the launch is just a few weeks away

**Comment by jni** [comment]
> I'm curious why wait until launch to merge?

I know what napari hub is, but most people don't. If I didn't already know what it was, I would be super confused by this file...

**Comment by jni** [comment]
But I'm also ok with having this merged. I leave this decision to higher powers ie @sofroniewn. :joy:

**Comment by sofroniewn** [comment]
We now have a https://www.napari-hub.org/ "coming soon" page and the repo https://github.com/chanzuckerberg/napari-hub is public. I think we're now close enough to launch that we can get this in. I will approve now. Will see if anyone else wants to comment before it goes in. @DragaDoncila is it still ready from your point of view?

**Review by sofroniewn — APPROVED** [review]

**Comment by DragaDoncila** [comment]
@sofroniewn it's ready to go, yes. It'll cause conflicts for #43 but I'll fix those once we merge.

**Pull request merged**
