### PR TITLE
Run git init automatically

### PR DESCRIPTION
**Pull request by tlambert03**
This PR tries to run `git init` automatically after creating the cookiecutter.  If it fails (perhaps if they don't have git installed), the usual message is shown, otherwise they can immediately install their package and use version control.

### CODE REVIEW

**Comment by DragaDoncila** [comment]
This looks good to me. Tried it out locally and it works fine. 

However also tried it on a machine with an older version of `git` (2.24) which doesn't support the `-b` switch. This then fails to create a repo, but the message printed is still the message we'd expect to see if initialisation worked:

```
(napari-edit) draga@DragaZenBook:~$ cookiecutter CZI/cookiecutter-napari-plugin/
full_name [Napari Developer]: Draga
email [yourname@example.com]: 
github_username_or_organization [githubuser]: 
plugin_name [napari-foobar]: napari-with-git
Select github_repository_url:
1 - https://github.com/githubuser/napari-with-git
2 - provide later
Choose from 1, 2 [1]: 
module_name [napari_with_git]: 
short_description [A simple plugin to use with napari]: 
include_reader_plugin [y]: 
include_writer_plugin [y]: 
include_dock_widget_plugin [y]: 
include_function_plugin [y]: 
use_git_tags_for_versioning [n]: y
Select docs_tool:
1 - mkdocs
2 - sphinx
3 - none
Choose from 1, 2, 3 [1]: 
Select license:
1 - BSD-3
2 - MIT
3 - Mozilla Public License 2.0
4 - Apache Software License 2.0
5 - GNU LGPL v3.0
6 - GNU GPL v3.0
Choose from 1, 2, 3, 4, 5, 6 [1]: 
error: unknown switch `b'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

Your plugin template is ready!  Next steps:

1. `cd` into your new directory

     cd napari-with-git
     # you probably want to install your new package into your env
     pip install -e .

2. Create a github repository with the name 'napari-with-git':
   https://github.com/new

...
```

The fact that there's an error message printed should hopefully be enough to alert users that something went wrong, but beginners may not know how to fix the issue without the `git init` instructions being printed.

@tlambert03 any idea why the exception wasn't caught?

**Comment by tlambert03** [comment]
Ah thanks!  We should probably add check=True to each run() call.  Could you maybe try that on the computer with old git?

**Comment by DragaDoncila** [comment]
@tlambert03 sorry for the delay on this. With `check=True` we still get the error message printed from git, but we get correct instructions from the user.

We can suppress `stdout` and `stderr` using `stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL` in our `run` calls - I'll leave it to you if you think that's better - we might end up silencing real errors though

**Comment by tlambert03** [comment]
> @tlambert03 I don't think I can push changes to your branch as I'm not a collaborator. Would you mind making these changes when you get a chance and we can merge this?

I added you as a collaborator, so you should be able to do most things here now (finally 😊 )

also, I changed the syntax to be compatible with older versions of git, so don't need to hide the errors

**Pull request merged**
